//% this code generated by Ai "github cobilot" ^-^
class config_generator;
    mailbox #(config_transaction) mb_gen_drv;
    mailbox #(config_transaction) mb_gen_mod;
    event driver_done;
    config_transaction transaction;

    function new(mailbox #(config_transaction) mb_drv, mailbox #(config_transaction) mb_mod, event driver_done);
        this.mb_gen_drv = mb_drv;
        this.mb_gen_mod = mb_mod;
        this.driver_done = driver_done;
    endfunction

    task generate_stimulus();
        bit first_time = 1;

        forever begin
            // Wait for driver_done event after the first time
            if (!first_time) @driver_done;

            // Create a new transaction and randomize it
            transaction = new();
            assert(transaction.randomize());

            //--- if we need a specific value for a field, we can set it here  
            //********************************************
            //********************************************
            //********************************************
            //********************************************
            
            // Put the transaction into the mailboxes
            config_transaction_mailbox1.put(transaction);
            config_transaction_mailbox2.put(transaction);

            first_time = 0;
        end
    endtask
endclass