//% this code generated by Ai "github cobilot" ^-^

class up_scoreboard;
  mailbox #(UL_mod_scr
  UL_mon_scr) UL_mod_scr;
  mailbox #(upper_layer_tr) UL_mon_scr;

  function new(mailbox #(upper_layer_tr) UL_mod_scr, mailbox #(upper_layer_tr) UL_mon_scr);
    this.UL_mod_scr = UL_mod_scr;
    this.UL_mon_scr = UL_mon_scr;
  endfunction: new

  task run_scr();
    upper_layer_tr mod_tr, scr_tr;

    forever begin
      UL_mod_scr.get(mod_tr);
      UL_mon_scr.get(scr_tr);

      // Display the values from mod_tr and scr_tr here
      $display("------------------------------");
      $display("Mod_tr: %0t, %m", $time, mod_tr);
      $display("Scr_tr: %0t, %m", $time, scr_tr);
      
      // and compare them to check if the values are same or not
      /* if (mod_tr.data != scr_tr.data) begin  //! make check part here 
        $error ("Data mismatch between monitored and model");
        $stop;
      end

      if (mod_tr.last != scr_tr.last) begin 
        $error ("Last bit mismatch between monitored and model");
        $stop;
        end*/
        


    end
  endtask: run_scr
  
endclass: upper_layer_scoreboard